[package]
name = "wld"
version = "0.1.0"
authors = ["Christopher Hiller <boneskull@boneskull.com>"]
edition = "2018"

[dependencies]
uuid = "0.8.1"
derive-new = "0.5.8"
scroll = { version = "0.10.1", features = ["derive", "std"] }
nano-leb128 = { version = "0.1.0", features = ["std"] }
bitvec = "0.17.2"

[dev-dependencies]
lazy_static = "1.4.0"
