[package]
name = "wld"
version = "0.1.0"
authors = ["Christopher Hiller <boneskull@boneskull.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.0"
uuid = "0.8.1"
derive-new = "0.5.8"
lazy_static = "1.4.0"

[dev-dependencies]
